version: 2
jobs:
  build:
    docker:
      - image: tampopos/node-dotnet:latest
    steps:
      - checkout
      - run:
          name: install packages
          command: npm i
      - run:
          name: test
          command: npm run test
